FROM debian:bookworm

RUN dpkg --add-architecture armhf && apt-get update && apt-get install -y gcc-arm-linux-gnueabihf libc6-dev:armhf libgtk-3-dev:armhf libglib2.0-dev:armhf pkg-config && rm -rf /var/lib/apt/lists/*

WORKDIR /src

CMD ["bash"]